
var makeid   = require('../config/utils.js').makeid;

module.exports = {
  "General Assembly 3": {
    "verificationID": makeid(6),
    "Afghanistan": false,
    "Argentina": false,
    "Australia": false,
    "Bahrain": false,
    "Bangledesh": false,
    "Belgium": false,
    "Bolivia": false,
    "Brazil": false,
    "Cambodia": false,
    "Canada": false,
    "China": false,
    "DPR Korea": false,
    "Egypt": false,
    "Ethiopia": false,
    "France": false,
    "Germany": false,
    "Hungary": false,
    "India": false,
    "Indonesia": false,
    "Iran": false,
    "Iraq": false,
    "Israel": false,
    "Italy": false,
    "Japan": false,
    "Jordan": false,
    "Kuwait": false,
    "Lebanon": false,
    "Mexico": false,
    "Mongolia": false,
    "Morocco": false,
    "Nepal": false,
    "Nigeria": false,
    "Oman": false,
    "Pakistan": false,
    "Palestine": false,
    "Philippines": false,
    "Poland": false,
    "Portugal": false,
    "Russia": false,
    "Saudi Arabia": false,
    "Singapore": false,
    "Spain": false,
    "Syria": false,
    "Taiwan": false,
    "Thailand": false,
    "Turkey": false,
    "Ukraine": false,
    "United Arab Emarites": false,
    "United Kingdom": false,
    "United States": false,
    "Venezuela": false,
    "Vietnam": false,
    "Yemen": false,
    "Zimbabwe": false
  },

  "General Assembly 4": {
    "verificationID": makeid(6),    
    "Afghanistan": false,
    "Australia": false,
    "Austria": false,
    "Bahrain": false,
    "Bangledesh": false,
    "Belgium": false,
    "Bhutan": false,
    "Bolivia": false,
    "Brazil": false,
    "Cambodia": false,
    "Canada": false,
    "Chad": false,
    "Chile": false,
    "China": false,
    "Cuba": false,
    "Czech Republic": false,
    "Denmark": false,
    "Dominican Rep.": false,
    "DPR Korea": false,
    "Ecuador": false,
    "Egypt": false,
    "France": false,
    "Germany": false,
    "Greece": false,
    "Haiti": false,
    "Honduras": false,
    "Hungary": false,
    "India": false,
    "Iran": false,
    "Iraq": false,
    "Ireland": false,
    "Israel": false,
    "Italy": false,
    "Japan": false,
    "Jordan": false,
    "Kuwait": false,
    "Lebanon": false,
    "Morocco": false,
    "Myanmar": false,
    "Nigeria": false,
    "Norway": false,
    "Oman": false,
    "Pakistan": false,
    "Palestine": false,
    "Philippines": false,
    "Qatar": false,
    "Russia": false,
    "Saudi Arabia": false,
    "Senegal": false,
    "Singapore": false,
    "South Korea": false,
    "Spain": false,
    "Sri Lanka": false,
    "Sweden": false,
    "Switzerland": false,
    "Thailand": false,
    "Turkey": false,
    "United Arab Emarites": false,
    "United Kingdom": false,
    "United States": false,
    "Uruguay": false,
    "Vietnam": false,
    "Yemen": false,
  },

  "Special Committee": {
    "verificationID": makeid(6),        
    "Argentina": false,
    "Bolivia": false,
    "Brazil": false,
    "Canada": false,
    "Chile": false,
    "China": false,
    "Colombia": false,
    "Costa Rica": false,
    "Dominican Republic": false,
    "DPR Korea": false,
    "Ecuador": false,
    "Egypt": false,
    "France": false,
    "Germany": false,
    "Haiti": false,
    "Honduras": false,
    "India": false,
    "Israel": false,
    "Italy": false,
    "Kenya": false,
    "Kuwait": false,
    "Lebanon": false,
    "Malaysia": false,
    "Mexico": false,
    "Netherlands": false,
    "Pakistan": false,
    "Palestine": false,
    "Paraguay": false,
    "Russia": false,
    "Saudi Arabia": false,
    "South Africa": false,
    "Spain": false,
    "Sweden": false,
    "United Kingdom": false,
    "Uruguay": false,
    "USA": false,
    "Venezuela": false,
  }
}


